### ISSUE TITLE
Init时候传入了路径，但你没有使用他

### ISSUE THREAD

**Issue by cnflysoft** [sndnvaps/Phonedata#2]

**Comment by sndnvaps** [comment]
你查看代码
https://github.com/sndnvaps/Phonedata/blob/master/phonedata/Phonedata.cs#L89
```csharp
        /// <summary>
        /// class phonedata 的构造函数
        /// </summary>
        public PhoneData(string phonedata)
        {
            Init(phonedata);
        }
```
我直接在构造函数里面调用了        
```csharp
public void Init(string phonedata)
```
https://github.com/sndnvaps/Phonedata/blob/master/phonedata/Phonedata.cs#L174
所以你得看一年代码，再来问问题

**Comment by cnflysoft** [comment]
https://github.com/sndnvaps/Phonedata/blob/master/phonedata/Phonedata.cs#L190
`FileStream fs = new FileStream("phone.dat", FileMode.OpenOrCreate, FileAccess.Read)`

现在给别人提点错误就这么不接受吗？

**Comment by sndnvaps** [comment]
@不好意思了大兄弟，我这个是做测试的，因为一直和 phonedata.dat文件放在一起，所以没有发现这个问题。
谢谢你的反馈，我已经修改了。

**Comment by sndnvaps** [comment]
已经更新，并推送到 nuget.org上面了。
可以用nuget来安装最新的了。。
